### ISSUE TITLE
new ld scripts for SDK 1.1.0 (rboot-sampleproject)

### ISSUE THREAD

**Issue by shanipribadi** [raburton/esp8266#3]
SDK 1.1.0 ld scripts has new sections in them (various ExceptionVector).

Running rboot-sampleproject that is compiled and linked using current rom*.ld and SDK 1.1.0 causes exception to be printed on serial monitor.

Booting rom 0.
Fatal exception (0):
epc1=0x40106f38, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

0x40106f38 is call_user_start on that rom0.elf

Using the new ld scripts from SDK 1.1.0 to compile and link them allow successfull running of the sampleproject.

on the latter rom0.elf call_user_start is on 0x40100004

**Comment by raburton** [comment]
thanks, will have a look at this once I get home, i had noticed it with my own apps but hadn't switched to building rboot with the new sdk
