### ISSUE TITLE
give rBoot it's own repo

### ISSUE THREAD

**Issue by morganrallen** [raburton/esp8266#33]
I've been using rBoot for a couple months now and I'm pretty much sold on it.

Now I'm just getting to the point I'm cleaning up my first project using it and with any
luck will be using it in an upcoming client project. With that it would be super handy
to have rBoot at a git submodule, but that requires it being in its own repo.

Hopefully this isn't an issue, thanks for you work on this, it's vastly improved my workflow.

**Comment by spants** [comment]
I'm also looking to tidy up my IoTBox project Richard - learning about using git submodules - so this would be handy for me too! Thanks for your help..

**Comment by morganrallen** [comment]
Fantastic! Thanks @raburton
