### ISSUE TITLE
compilation error with timezone.c. using esp_open_sdk  on linux environment.

### ISSUE THREAD

**Issue by SivaNallamalli** [raburton/esp8266#35]
ntp/timezone.c:10:31: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'applyTZ'
 static void ICACHE_FLASH_ATTR applyTZ(struct tm *time) {
                               ^
Makefile:149: recipe for target 'build/ntp/timezone.o' failed

**Comment by raburton** [comment]
Your sdk doesn't appear to use ICACHE_FLASH_ATTR to put functions in rom (rather than ram). Removing ICACHE_FLASH_ATTR will get rid of the error, but whether the function ends up in ram or rom (or how you would force it to one or the other) I can't say with your setup.
