### ISSUE TITLE
DS1307 - Supply Voltage

### ISSUE THREAD

**Issue by RichardPar** [raburton/esp8266#36]
Reading your comments on the DS1307 being flaky, I think it should be noted that it doesn't run from 3v3 - its a 5V part. DS1307 is not suited to for a ESP8266 (I now have 5 useless clocks! :)

The latter device can run in the range of 3v to 5v 

Richard

**Comment by raburton** [comment]
Not had much luck with them under any conditions. They generally won't even keep their time with battery backup. I'm sure all of these are counterfeit chips, but the ds3231 seem to be much better - more features, work better, same cost.
