### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pfalcon** [raburton/esp8266#6]
From https://github.com/raburton/esp8266/blob/master/rboot/readme.txt : 

> - Open source (written in C).

A project is not open source unless it comes with (explicit) Open Source license. Please add a LICENSE file which discloses licensing terms (as this repository contains multiple projects, each of them should rather have separate LICENSE file (consider a case of someone tarring up a subdirectory); also consider splitting up different projects to separate repos).

Thanks.

**Comment by raburton** [comment]
while your premise is incorrect, the suggestion to add a license is sensible (I did for esptool2, but didn't think to do so for the rest), it will be done...
